package Mail;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.mail.Message;

public class ResetPass {
    public static boolean sendEmail(String to, String pass){
        // Put recipient’s address
//        String to = "trungtuyenhocgioi@gmail.com";

        // Put sender’s address
        String from = "tuyenntph29022@fpt.edu.vn";
        // username + password email ma gui mail reset mat khau di
        final String username = "tuyenntph29022@fpt.edu.vn";//username generated by Mailtrap
        final String password = "ngotrungtuyen17032003";//password generated by Mailtrap

        // Paste host address from the SMTP settings tab in your Mailtrap Inbox
        String host = "smtp.gmail.com";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "587");// use one of the options in the SMTP settings tab in your Mailtrap Inbox
        
        // Get the Session object.
        Session session = Session.getInstance(props,
            new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
//                protected PasswordAuthentication getPasswordAuthentication() {
//                    return new PasswordAuthentication(username, password);
//                }
            });

        try {
            
            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);

            // Set From: header field
            message.setFrom(new InternetAddress(from));

            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject("Reset your password.");

            // Put the content of your message
            message.setText("Your new password: " + pass);
            
            // Send message
            Transport.send(message);
            System.out.println("Sent message successfully....");
            return true;
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
}

