/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.ThanhPhan;

import DomainModels.Coupon;
import Service.CouponService;
import Service.Interface.ICouponService;
import ViewModel.CouponModel;
import com.barcodelib.barcode.Linear;
import java.lang.ref.Cleaner;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WellCome Win1021H2
 */
public class QL_Coupon extends javax.swing.JFrame {

    private ICouponService iCouponService = (ICouponService) new CouponService();
    private DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form QL_Coupon
     */
    public QL_Coupon() {
        initComponents();
        dtm = (DefaultTableModel) tblHienThi.getModel();
        this.loadData();

    }

    public void loadData() {
        ArrayList<CouponModel> list = iCouponService.getAllCoupon();
        dtm.setRowCount(0);
        Collections.sort(list, Comparator.comparing(Coupon -> Coupon.getId()));
        for (CouponModel x : list) {
            dtm.addRow(new Object[]{
                x.getMa(),
                x.getHanSuDung(),
                x.getHinhThuc(),
                x.getGiamGia()
            });
        }
    }

    public CouponModel getFromData() throws ParseException {
        double random = Math.random();
        random = random * 99999999 + 10000000;
        int ma = (int) random;
        String maCoupon = "";
        for (CouponModel c : iCouponService.getAllCoupon()) {
            if (c.getMa()!=null && c.getMa().equals(String.valueOf(ma))) {
                ma += 1;
            }
        }
        maCoupon = String.valueOf(ma);

        Date hanSuDung = txtHanSuDung.getDate();
        System.out.println(hanSuDung);
//        Date hsd = new SimpleDateFormat("dd/MM/yyyy").parse(hanSuDung.toString());
//        System.out.println(hsd);
        String giamGia = txtGiamGia.getText();
        int hinhThuc = cbbHinhThuc.getSelectedIndex();
        String ht = "";
        if (hinhThuc == 0) {
            ht = "Giảm tiền";
        } else if (hinhThuc == 1) {
            ht = "Giảm phần trăm";
        }
        if (giamGia.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giảm giá không được để trống");
            return null;
        }
        if (hanSuDung == null) {
            JOptionPane.showMessageDialog(this, "Hạn sử dụng không được để trống");
            return null;
        }
        return new CouponModel(null, maCoupon, hanSuDung, ht, Float.valueOf(giamGia), null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldCoupon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        cbbHinhThuc = new javax.swing.JComboBox<>();
        txtHanSuDung = new com.toedter.calendar.JDateChooser();
        Nút = new javax.swing.JPanel();
        btnSua = new javax.swing.JButton();
        btnThemSP = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnInMa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coupon");

        TextFieldCoupon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã Coupon:");

        jLabel3.setText("Hạn sử dụng:");

        jLabel4.setText("Hình thức:");

        jLabel5.setText("Giảm giá:");

        txtMa.setEnabled(false);

        cbbHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm tiền", "Giảm phần trăm" }));

        javax.swing.GroupLayout TextFieldCouponLayout = new javax.swing.GroupLayout(TextFieldCoupon);
        TextFieldCoupon.setLayout(TextFieldCouponLayout);
        TextFieldCouponLayout.setHorizontalGroup(
            TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextFieldCouponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextFieldCouponLayout.setVerticalGroup(
            TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextFieldCouponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TextFieldCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThemSP.setText("Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnInMa.setText("In Mã");
        btnInMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NútLayout = new javax.swing.GroupLayout(Nút);
        Nút.setLayout(NútLayout);
        NútLayout.setHorizontalGroup(
            NútLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NútLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInMa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        NútLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInMa, btnSua, btnThemSP});

        NútLayout.setVerticalGroup(
            NútLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NútLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NútLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NútLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSua)
                        .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInMa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NútLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInMa, btnSua, btnThemSP});

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Coupon", "Thời hạn", "Hình thức", "Giảm giá"
            }
        ));
        tblHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHienThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHienThi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldCoupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nút, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nút, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        try {
            CouponModel cp = getFromData();
            if (cp == null) {
                return;
            }
            if (iCouponService.insertCP(cp) != null) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            int index = tblHienThi.getSelectedRow();
            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Chọn dòng cần sửa");
            }
            CouponModel cp = getFromData();
            if (cp == null) {
                return;
            }
            String ma = tblHienThi.getValueAt(index, 0).toString();
            ArrayList<CouponModel> list = iCouponService.getAllCoupon();
            String id = "";
            for (CouponModel x : list) {
                if (x.getMa() != null && x.getMa().equals(ma)) {
                    id = x.getId();
                }
            }
            cp.setId(id);
            if (iCouponService.updateCP(cp) != null) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHienThiMouseClicked
        try {
            int index = tblHienThi.getSelectedRow();
            String ma = tblHienThi.getValueAt(index, 0).toString();
            String hanSuDung = tblHienThi.getValueAt(index, 1).toString();
            String theLoai = tblHienThi.getValueAt(index, 2).toString();
            String giamGia = tblHienThi.getValueAt(index, 3).toString();
            txtMa.setText(ma);
            Date hsd = new SimpleDateFormat("yyyy-MM-dd").parse(hanSuDung);
            System.out.println(hanSuDung);
            System.out.println(hsd);
            int tl = 0;
            if (theLoai.trim().equals("Giảm tiền")) {
                tl = 0;
            } else if (theLoai.trim().equals("Giảm phần trăm")) {
                tl = 1;
            }
            txtHanSuDung.setDate(hsd);
            txtGiamGia.setText(giamGia);
            cbbHinhThuc.setSelectedIndex(tl);
        } catch (ParseException ex) {
            Logger.getLogger(QL_Coupon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblHienThiMouseClicked

    private void btnInMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInMaActionPerformed
        int row = tblHienThi.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sp bạn muốn in mã");
            return;
        }
        String ma = tblHienThi.getValueAt(row, 0).toString();
        try {
            Linear barcode = new Linear();
            barcode.setType(Linear.CODE128B);
            barcode.setData(ma);
            barcode.setI(11.0f);
            String maqr = ma;
            barcode.renderBarcode("D:\\DuAn1_FInal\\src\\BarcoreSP\\" + maqr + ".png");
            JOptionPane.showMessageDialog(this, "Tạo mã thành công");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_Coupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_Coupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_Coupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_Coupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_Coupon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nút;
    private javax.swing.JPanel TextFieldCoupon;
    private javax.swing.JButton btnInMa;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JComboBox<String> cbbHinhThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextField txtGiamGia;
    private com.toedter.calendar.JDateChooser txtHanSuDung;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
